# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/telemetry.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/telemetry.proto\x12\x0ctelemetry.v1\"\xda\x02\n\x06Sample\x12\x19\n\x11timestamp_unix_ns\x18\x01 \x01(\x03\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x13\n\x0bsource_type\x18\x03 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x04 \x01(\t\x12\x11\n\tentity_id\x18\x05 \x01(\t\x12\x13\n\x0bmetric_name\x18\x06 \x01(\t\x12\x0c\n\x04unit\x18\x07 \x01(\t\x12\x16\n\x0eis_categorical\x18\x08 \x01(\x08\x12\r\n\x05value\x18\t \x01(\x01\x12\x13\n\x0b\x64\x65lta_short\x18\n \x01(\x01\x12\x12\n\ndelta_long\x18\x0b \x01(\x01\x12\x13\n\x0brolling_var\x18\x0c \x01(\x01\x12\x30\n\x06labels\x18\r \x03(\x0b\x32 .telemetry.v1.Sample.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x05\x42\x61tch\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1f\n\x17\x62\x61tch_timestamp_unix_ns\x18\x02 \x01(\x03\x12%\n\x07samples\x18\x03 \x03(\x0b\x32\x14.telemetry.v1.SampleB<Z:github.com/aladed/JINR/edge-agent/internal/transport/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/aladed/JINR/edge-agent/internal/transport/pb;pb'
  _globals['_SAMPLE_LABELSENTRY']._loaded_options = None
  _globals['_SAMPLE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLE']._serialized_start=40
  _globals['_SAMPLE']._serialized_end=386
  _globals['_SAMPLE_LABELSENTRY']._serialized_start=341
  _globals['_SAMPLE_LABELSENTRY']._serialized_end=386
  _globals['_BATCH']._serialized_start=388
  _globals['_BATCH']._serialized_end=484
# @@protoc_insertion_point(module_scope)
