// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/transport/telemetry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sample struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // source host
	SourceType      string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	EntityType      string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // cpu|gpu|hdd|ram|switch|job|link
	EntityId        string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	MetricName      string                 `protobuf:"bytes,6,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"` // exactly from §1.2 contract
	Unit            string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	IsCategorical   bool                   `protobuf:"varint,8,opt,name=is_categorical,json=isCategorical,proto3" json:"is_categorical,omitempty"` // true → only value is meaningful
	Value           float64                `protobuf:"fixed64,9,opt,name=value,proto3" json:"value,omitempty"`
	DeltaShort      float64                `protobuf:"fixed64,10,opt,name=delta_short,json=deltaShort,proto3" json:"delta_short,omitempty"`                                               // 0 for categorical
	DeltaLong       float64                `protobuf:"fixed64,11,opt,name=delta_long,json=deltaLong,proto3" json:"delta_long,omitempty"`                                                  // 0 for categorical
	RollingVar      float64                `protobuf:"fixed64,12,opt,name=rolling_var,json=rollingVar,proto3" json:"rolling_var,omitempty"`                                               // 0 for categorical
	Labels          map[string]string      `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // job_id, rack, gpu_index, switch_role, link_type...
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_internal_transport_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_internal_transport_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

func (x *Sample) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Sample) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Sample) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Sample) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Sample) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Sample) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Sample) GetIsCategorical() bool {
	if x != nil {
		return x.IsCategorical
	}
	return false
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sample) GetDeltaShort() float64 {
	if x != nil {
		return x.DeltaShort
	}
	return 0
}

func (x *Sample) GetDeltaLong() float64 {
	if x != nil {
		return x.DeltaLong
	}
	return 0
}

func (x *Sample) GetRollingVar() float64 {
	if x != nil {
		return x.RollingVar
	}
	return 0
}

func (x *Sample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Batch struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BatchTimestampUnixNs int64                  `protobuf:"varint,2,opt,name=batch_timestamp_unix_ns,json=batchTimestampUnixNs,proto3" json:"batch_timestamp_unix_ns,omitempty"`
	Samples              []*Sample              `protobuf:"bytes,3,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_internal_transport_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_internal_transport_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Batch) GetBatchTimestampUnixNs() int64 {
	if x != nil {
		return x.BatchTimestampUnixNs
	}
	return 0
}

func (x *Batch) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

var File_internal_transport_telemetry_proto protoreflect.FileDescriptor

const file_internal_transport_telemetry_proto_rawDesc = "" +
	"\n" +
	"\"internal/transport/telemetry.proto\x12\ftelemetry.v1\"\xf4\x03\n" +
	"\x06Sample\x12*\n" +
	"\x11timestamp_unix_ns\x18\x01 \x01(\x03R\x0ftimestampUnixNs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12\x1f\n" +
	"\vmetric_name\x18\x06 \x01(\tR\n" +
	"metricName\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12%\n" +
	"\x0eis_categorical\x18\b \x01(\bR\risCategorical\x12\x14\n" +
	"\x05value\x18\t \x01(\x01R\x05value\x12\x1f\n" +
	"\vdelta_short\x18\n" +
	" \x01(\x01R\n" +
	"deltaShort\x12\x1d\n" +
	"\n" +
	"delta_long\x18\v \x01(\x01R\tdeltaLong\x12\x1f\n" +
	"\vrolling_var\x18\f \x01(\x01R\n" +
	"rollingVar\x128\n" +
	"\x06labels\x18\r \x03(\v2 .telemetry.v1.Sample.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x05Batch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\x17batch_timestamp_unix_ns\x18\x02 \x01(\x03R\x14batchTimestampUnixNs\x12.\n" +
	"\asamples\x18\x03 \x03(\v2\x14.telemetry.v1.SampleR\asamplesB<Z:github.com/aladed/JINR/edge-agent/internal/transport/pb;pbb\x06proto3"

var (
	file_internal_transport_telemetry_proto_rawDescOnce sync.Once
	file_internal_transport_telemetry_proto_rawDescData []byte
)

func file_internal_transport_telemetry_proto_rawDescGZIP() []byte {
	file_internal_transport_telemetry_proto_rawDescOnce.Do(func() {
		file_internal_transport_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_telemetry_proto_rawDesc), len(file_internal_transport_telemetry_proto_rawDesc)))
	})
	return file_internal_transport_telemetry_proto_rawDescData
}

var file_internal_transport_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_transport_telemetry_proto_goTypes = []any{
	(*Sample)(nil), // 0: telemetry.v1.Sample
	(*Batch)(nil),  // 1: telemetry.v1.Batch
	nil,            // 2: telemetry.v1.Sample.LabelsEntry
}
var file_internal_transport_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.v1.Sample.labels:type_name -> telemetry.v1.Sample.LabelsEntry
	0, // 1: telemetry.v1.Batch.samples:type_name -> telemetry.v1.Sample
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_transport_telemetry_proto_init() }
func file_internal_transport_telemetry_proto_init() {
	if File_internal_transport_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_telemetry_proto_rawDesc), len(file_internal_transport_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_transport_telemetry_proto_goTypes,
		DependencyIndexes: file_internal_transport_telemetry_proto_depIdxs,
		MessageInfos:      file_internal_transport_telemetry_proto_msgTypes,
	}.Build()
	File_internal_transport_telemetry_proto = out.File
	file_internal_transport_telemetry_proto_goTypes = nil
	file_internal_transport_telemetry_proto_depIdxs = nil
}
